### ISSUE TITLE
Installed requirements in container not recognized

### ISSUE THREAD

**Issue by Lars** [meanmail-dev/requirements#45]
Using a Docker container to dev/build/run the project (using a python module inside the project with the right docker based SDK selected, and the whole project also has same SDK selected). When editing requirements.txt all requirements are marked as not installed, even if they are installed on the container (part of the build process is copying said requirements.txt file and installing all listed within).

**Comment by meanmail** [comment]
The plugin doesn't know anything about the docker container. The plugin always checks packages in the environment specified in the project (https://www.jetbrains.com/help/idea/sdk.html#change-project-sdk)

Perhaps in the future you can add a setting so that the plugin can watch others surrounded....

**Comment by meanmail** [comment]
Fixed in 2021.4
